### ISSUE TITLE
Provider Meta-Description in applications.properties

### ISSUE THREAD

**Issue by BlackRose01** [arrowhead-f/client-java-spring#11]
Hello,

is there any way to include the provider's meta-description in the applications.properties? This would make the work a lot easier, since source code does not have to be adapted every time.  Of course it would also be possible to load an external file. But with large descriptions with the JSON convention, this can be very confusing and can be a tedious task when forgetting a character.

Many Thanks.
BlackRose01

**Comment by rbocsi** [comment]
Hello,

The application.properties is just a standard Java properties file, so you can add custom parameters if you want. 

You can add multiple line property value if you ends the line with \. You can also use control characters in the property value, for example \n to indicate new line in the value. Please note, you also have to escape , (comma) if you use it in the text, because comma have special meaning in the properties file.

Here an example:

_application.properties_
`provider.description=This is a long\, multi-lined text.\n \`
`This is just a test.`

Then I can access this property in the Java code (for example in the controller class):

`@Value("${provider.description}")`
`private String description;`

If I print the value the output should be something like this:

_This is a long, multi-lined text.
This is just a test._

Now, If you want to store JSON in a property you can do that too, just please remember you have to escape commas. For example:

`provider.meta={"key1": "value1" \, \`
`"key2": "value2" \`
`}`

Output:

_{"key1": "value1" , "key2": "value2" }_

Hope it helps.

**Comment by BlackRose01** [comment]
Thank you.

In the old version of the client you could enter it in the configuration file. That's why I was so surprised when the complete option didn't exist anymore.  Also I couldn't find anything in the library or in the description.

**Comment by borditamas** [comment]
Hello,
the old version had assumed, that one provider has only one service, which is not the case in lot of scenario. Handling multiple services with their details from the properties file makes it cluttered. Of course if your implementation require to managing the service details from the prop file, you can do it as @rbocsi has described.
